# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fb312bc7ace45e07c816b94af5f7dce8c4a6b4cf2e4931839ddad2852390a8e32502d596153fb13c448b1f4081ce1325610f5ef3b51f9c0b0f9881edd453bad

test:
  secret_key_base: 1d0500e0706c310af9e97341d27c1f9837667a1712dfa0cd85cf988e264f413bc33b91159a36a222cf184006818ccf4137c934d8d3b3ffe429baf50c3c44eda9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
